[package]
name = "samlang-wasm"
version = "0.8.0"
edition = "2021"

[dependencies]
samlang-core = { path = "../samlang-core" }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"

[lib]
crate-type = ["cdylib", "rlib"]
