plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-generate-workspaces-json.cjs
    spec: "https://raw.githubusercontent.com/SamChou19815/website/master/.yarn/plugins/%40yarnpkg/plugin-generate-workspaces-json.cjs"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
