plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-monorail.cjs
    spec: 'https://raw.githubusercontent.com/SamChou19815/infra/main/.yarn/plugins/%40yarnpkg/plugin-monorail.cjs'

yarnPath: .yarn/releases/yarn-3.1.0-rc.11.cjs
