plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-monorail.cjs
    spec: yarn-plugin-monorail/bundles/plugin-monorail.js

yarnPath: .yarn/releases/yarn-3.0.1.cjs
