[workspace]
members = [
  "crates/samlang-core",
  "crates/samlang-collections",
  "crates/samlang-cli",
  "crates/samlang-errors",
  "crates/samlang-heap",
  "crates/samlang-wasm",
]
resolver = "2"

[profile.release]
lto = true
strip = true
