rootProject.name = "samlang"
include("samlang-ast")
include("samlang-checker")
include("samlang-errors")
include("samlang-utils")
include("samlang-parser-generated")
include("samlang-parser")
include("samlang-interpreter")
include("samlang-analysis")
include("samlang-optimization")
include("samlang-compiler")
include("samlang-printer")
