rootProject.name = "samlang"
include(
    "samlang-ast",
    "samlang-checker",
    "samlang-errors",
    "samlang-utils",
    "samlang-parser-generated-java",
    "samlang-parser",
    "samlang-interpreter",
    "samlang-analysis",
    "samlang-optimization",
    "samlang-compiler-hir",
    "samlang-compiler-mir",
    "samlang-compiler-asm",
    "samlang-printer",
    "samlang-service",
    "samlang-demo",
    "samlang-cli"
)
