[alias]
t = "nextest run"
tc = "llvm-cov nextest --fail-under-lines 100 --fail-uncovered-lines 0 --fail-uncovered-functions 0 --ignore-filename-regex=main.rs"
th = "llvm-cov nextest --html --show-missing-lines --ignore-filename-regex=main.rs"
lint = "clippy"
