import type { SourceFieldType } from '../ast/samlang-nodes';
import {
  SamlangType,
  SamlangUndecidedType,
  SourceFunctionType,
  SourceIdentifierType,
  SourceTupleType,
  UndecidedTypes,
} from '../ast/samlang-nodes';
import { assert, zip } from '../utils';

/**
 * This modules is useful for doing type inference constraint solving on constructors/functions with
 * generic arguments.
 *
 * We can turn those parameter types CONSISTENTLY into undecided types, and use the same type
 * inference engine to solve it.
 */

export function typeReplacement(
  type: SamlangType,
  mapping: Readonly<Record<string, SamlangType>>
): SamlangType {
  assert(type.type !== 'UndecidedType', 'Type expression should not contain undecided type!');
  switch (type.type) {
    case 'PrimitiveType':
      return type;
    case 'IdentifierType':
      if (type.typeArguments.length === 0) {
        return mapping[type.identifier] ?? type;
      }
      return SourceIdentifierType(
        type.moduleReference,
        type.identifier,
        type.typeArguments.map((it) => typeReplacement(it, mapping))
      );
    case 'TupleType':
      return SourceTupleType(type.mappings.map((it) => typeReplacement(it, mapping)));
    case 'FunctionType':
      return SourceFunctionType(
        type.argumentTypes.map((it) => typeReplacement(it, mapping)),
        typeReplacement(type.returnType, mapping)
      );
  }
}

/**
 * Given a `type` and its `typeParameters`, replaces all references to type parameters to freshly
 * created undecided types.
 *
 * @return (`type` with `typeParameters` replaced with undecided types, generated undecided types).
 */
export function undecideTypeParameters(
  type: SamlangType,
  typeParameters: readonly string[]
): readonly [SamlangType, readonly SamlangUndecidedType[]] {
  const autoGeneratedUndecidedTypes = UndecidedTypes.nextN(typeParameters.length);
  const replacementMap = Object.fromEntries(zip(typeParameters, autoGeneratedUndecidedTypes));
  return [typeReplacement(type, replacementMap), autoGeneratedUndecidedTypes];
}

/**
 * Given a `typeMappings` and its `typeParameters`, replaces all references to type parameters to
 * freshly created undecided types.
 *
 * @return tuple(
 *  `typeMappings` with `typeParameters` replaced with undecided types,
 *   generated undecided types
 * ).
 */
export function undecideFieldTypeParameters(
  typeMappings: Record<string, SourceFieldType>,
  typeParameters: readonly string[]
): readonly [Record<string, SourceFieldType>, readonly SamlangUndecidedType[]] {
  const autoGeneratedUndecidedTypes = UndecidedTypes.nextN(typeParameters.length);
  const replacementMap = Object.fromEntries(zip(typeParameters, autoGeneratedUndecidedTypes));
  const newTypeMappings = Object.fromEntries(
    Object.entries(typeMappings).map(([name, fieldType]) => {
      return [
        name,
        { isPublic: fieldType.isPublic, type: typeReplacement(fieldType.type, replacementMap) },
      ] as const;
    })
  );
  return [newTypeMappings, autoGeneratedUndecidedTypes];
}
