#!/bin/bash

set -e
set -x

cp ../samlang-parser-generated-java/src/main/antlr/PL.g4 .
cp ../samlang-parser-generated-java/src/main/antlr/PLLexerPart.g4 .
rm -rf src/generated
mkdir src/generated
yarn antlr4ts -o src/generated -visitor PL.g4
rm PL*.g4
yarn tsc
yarn dukat -d ../samlang-parser/src/jsMain/kotlin/samlang/parser/ lib/index.d.ts
