[package]
name = "samlang-ast"
version = "0.9.1"
edition = "2021"

[dependencies]
enum-as-inner = "0.5.1"
enum-iterator = "1.4.1"
itertools = "0.12.1"
samlang-heap = { path = "../samlang-heap" }

[dev-dependencies]
pretty_assertions = "1.4.0"
