; Generated by Clang, and hand removed a few complicated stuff.

define i64 @factorial(i64 %0) local_unnamed_addr nounwind {
  %2 = icmp slt i64 %0, 2
  br i1 %2, label %9, label %3

3:                                                ; preds = %1, %3
  %4 = phi i64 [ %6, %3 ], [ %0, %1 ]
  %5 = phi i64 [ %7, %3 ], [ 1, %1 ]
  %6 = add i64 %4, -1
  %7 = mul i64 %4, %5
  %8 = icmp slt i64 %4, 3
  br i1 %8, label %9, label %3

9:                                                ; preds = %3, %1
  %10 = phi i64 [ 1, %1 ], [ %7, %3 ]
  ret i64 %10
}

define void @compiled_program_main(i64** %0) local_unnamed_addr nounwind {
  %t0 = call i64 @factorial(i64 30) nounwind
  %t1 = call i64* @builtin_intToString(i64 %t0) nounwind
  call void @builtin_println(i64* %t1) nounwind
  ret void
}

declare void @builtin_println(i64*) nounwind

declare i64* @builtin_intToString(i64) nounwind
