[package]
name = "samlang-errors"
version = "0.9.1"
edition = "2021"

[dependencies]
itertools = "0.12.0"
samlang-ast = { path = "../samlang-ast" }
samlang-heap = { path = "../samlang-heap" }

[dev-dependencies]
pretty_assertions = "1.4.0"
