[alias]
t = "nextest run"
tc = "llvm-cov nextest --fail-under-lines 100 --fail-uncovered-lines 0 --fail-uncovered-functions 0 --show-missing-lines --ignore-filename-regex=(main.rs)|(samlang-wasm)"
th = "llvm-cov nextest --fail-under-lines 100 --fail-uncovered-lines 0 --fail-uncovered-functions 0 --html --show-missing-lines --ignore-filename-regex=(main.rs)|(samlang-wasm)"
lint = "clippy --no-deps --tests"
