[package]
name = "samlang-cli"
version = "0.8.0"
edition = "2021"

[dependencies]
samlang-core = { path = "../samlang-core" }
serde_json = "1.0"
tokio = { version = "1.23.0", features = ["full"] }
tower-lsp = "0.17.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
