[package]
name = "samlang-cli"
version = "0.8.0"
edition = "2021"

[dependencies]
samlang-core = { path = "../samlang-core" }
serde_json = "1.0"
tokio = { version = "1.23.1", features = ["io-util", "io-std", "macros", "rt-multi-thread"] }
tower-lsp = "0.18.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
