#!/bin/sh

unzip samlang-runtime/wasi-libc.zip -d samlang-runtime
cd samlang-runtime/wasi-libc-main
make install INSTALL_DIR=../compiled-wasi-libc
cd ../../
rm -rf samlang-runtime/wasi-libc-main
clang \
  --target=wasm32-unknown-wasi \
  --sysroot amlang-runtime/compiled-wasi-libc \
  -D WASM_MODE \
  -nostartfiles \
  -Wl,--import-memory \
  -Wl,--no-entry \
  -Wl,--export-all \
  -o test.wasm samlang-runtime/gc.c
