#!/bin/bash

set -e

# Build all programs.
cd runtime
make > /dev/null
cd ../
./gradlew build

# TODO: unbreak it once ts-rewrite finishes
# Create release folder
# rm -rf build/release
# mkdir build/release
# mkdir build/release/build
# mkdir build/release/build/libs
# mkdir build/release/runtime
# cp build/libs/samlang-all.jar build/release/build/libs
# cp runtime/libsam.a build/release/runtime
# echo '#!/bin/bash
# MY_PATH=$(dirname "$0")
# JAR_PATH="${MY_PATH}"/build/libs/samlang-all.jar
# java -jar "$JAR_PATH" "$@"' > build/release/samlang
# chmod +x build/release/samlang
