#!/bin/bash

# Fail on any integration test fail.
set -e

./samlang-dev compile

# TS
echo '{
  "compilerOptions": {
    "rootDir": ".",
    "noEmit": true
  }
}' > ./out/ts/tsconfig.json
echo 'Checking generating TS code...' >&2
tsc -p out/ts/tsconfig.json

# Java
echo 'Checking generating Java code...' >&2
find out/java/ -name "*.java" > sources.txt
javac -cp ./out/java @sources.txt
rm ./out/java/**/*.class
rm sources.txt
