[package]
name = "samlang-core"
version = "0.8.0"
edition = "2021"

[dependencies]
enum-as-inner = "0.5.1"
enum-iterator = "1.2.0"
itertools = "0.10.5"
wat = "1.0.56"

[dev-dependencies]
pretty_assertions = "1.3.0"
wasmi = "0.20.0"
