name: CI for Kotlin Code
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci-kt.yml'
      - 'runtime/**'
      - 'sconfig.json'
      - '**.samlang'
      - 'scripts/**'
      - 'test/**'
      - '**.kt'
      - '**.kts'
  pull_request:
    paths:
      - '.github/workflows/ci-kt.yml'
      - 'runtime/**'
      - 'sconfig.json'
      - '**.samlang'
      - 'scripts/**'
      - 'test/**'
      - '**.kt'
      - '**.kts'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build
