name: Runtime
on:
  push:
    branches:
      - master
    paths:
      - 'runtime/**'
  pull_request:
    paths:
      - 'runtime/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '11'
          directory: ${{ runner.temp }}/llvm
      - name: Build runtime
        run: cd runtime && make
      - name: Build example
        run: cd runtime && make example
      - name: Run example code
        run: cd runtime && ./example
