name: CI
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./scripts/release
      - name: Verify that Release Program Works
        run: ./build/release/samlang
      - name: Compile samlang Programs
        run: ./scripts/compile-repository.js
      - name: Validate TS distribution
        run: |
          ./scripts/copy-demo-distribution-ts
          cd samlang-demo-distribution-ts
          yarn
          yarn test
  typescript-rewrite-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript-rewrite
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            typescript-rewrite/.yarn/cache
            typescript-rewrite/.pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-berry-
      - name: Yarn Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Check Format
        run: yarn format:check
