name: CI for TypeScript Code
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: |
            typescript-rewrite/.yarn/cache
            typescript-rewrite/.pnp.js
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-berry-
      - name: Yarn Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Check Format
        run: yarn format:check
      - name: Compile runtime
        run: cd ../runtime && make
      - name: Compile samlang Programs
        run: cd ../ && ./scripts/compile-repository.js
