name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: SamChou19815/infra/actions/setup-node-project@main
      - name: Format Check
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: SamChou19815/infra/actions/setup-node-project@main
        with:
          historyForDiff: true
      - name: Compile
        run: pnpm compile --filter "..[${{ github.event.pull_request.base.sha }}]"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: SamChou19815/infra/actions/setup-node-project@main
      - name: Test
        run: pnpm test
      - name: Compile samlang Programs
        run: pnpm test:integration
