name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Format Check
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Compile
        run: pnpm compile
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
      - name: Compile samlang Programs
        run: pnpm test:integration
