name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-per-os:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - name: Build samlang and compile samlang source code
        run: |
          corepack enable
          pnpm install
          node platform-independent-build.js
          pnpm samlang
      - uses: actions/upload-artifact@v3
        with:
          name: samlang-cli-${{ matrix.os }}
          path: packages/samlang-cli/bin
  build:
    needs: build-per-os
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-ubuntu-latest
          path: packages/samlang-cli/linux/
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-macos-12
          path: packages/samlang-cli/macos/
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-windows-latest
          path: packages/samlang-cli/windows/
      - name: Move artifacts
        run: |
          cd packages/samlang-cli
          mv linux/* bin
          mv macos/* bin
          mv windows/* bin
          rm -rf linux macos windows
      - uses: actions/upload-artifact@v3
        with:
          name: samlang-cli
          path: ./packages/samlang-cli
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo lint
      - name: Build & Test
        run: cargo tc && ./compile-repository.sh
