name: Full Integration Test
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/full-integration-test.yml
      - scripts/compile-repository.js
      - scripts/snapshot.txt
      - test/*.sam
      - samlang-runtime/*
      - samlang-cli/samlang-runtime/*

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: ".yarn/cache\n.pnp.js"
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@master
        with:
          version: '11'
          directory: ${{ runner.temp }}/llvm
      - name: Compile Runtime
        run: make && cp samlang-runtime/runtime.bc samlang-cli/samlang-runtime/libsam-linux.bc
      - name: Compile samlang Programs
        run: yarn test:integration
