name: Integration Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: ".yarn/cache\n.pnp.js"
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn
      - name: Compile samlang Programs
        run: yarn test:integration
