name: LLVM Migration
on:
  pull_request:
    paths:
      - 'runtime/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compile to LLVM
        run: |
          cd runtime
          make llvm
