name: Release
on:
  push:
    tags: ['v*.*.*']

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Targets
        run: |
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: |
          cargo b -p samlang-cli --release --target aarch64-unknown-linux-gnu
          cargo b -p samlang-cli --release --target x86_64-unknown-linux-gnu
          mkdir bin
          cp target/aarch64-unknown-linux-gnu/release/samlang-cli bin/samlang-aarch64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnurelease/samlang-cli bin/samlang-x86_64-unknown-linux-gnu
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: samlang-cli-linux
          path: bin

  build-mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Targets
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin
      - name: Build
        run: |
          cargo b -p samlang-cli --release --target aarch64-apple-darwin
          cargo b -p samlang-cli --release --target x86_64-apple-darwin
          mkdir bin
          cp target/aarch64-apple-darwin/release/samlang-cli bin/samlang-x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/samlang-cli bin/samlang-x86_64-apple-darwin
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: samlang-cli-mac
          path: bin

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Targets
        run: |
          rustup target add aarch64-pc-windows-msvc
          rustup target add x86_64-pc-windows-msvc
      - name: Build
        run: |
          cargo b -p samlang-cli --release --target aarch64-pc-windows-msvc
          cargo b -p samlang-cli --release --target x86_64-pc-windows-msvc
          mkdir bin
          cp target/aarch64-pc-windows-msvc/release/samlang-cli bin/samlang-aarch64-pc-windows-msvc
          cp target/x86_64-pc-windows-msvc/release/samlang-cli bin/samlang-x86_64-pc-windows-msvc
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: samlang-cli-windows
          path: bin

  release:
    needs:
      - build-linux
      - build-mac
      - build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-linux
          path: linux/
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-mac
          path: macos/
      - uses: actions/download-artifact@v3
        with:
          name: samlang-cli-windows
          path: windows/
      - name: Move artifacts
        run: |
          mkdir bin
          mv linux/* bin
          mv macos/* bin
          mv windows/* bin
          rm -rf linux macos windows
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'bin/samlang-*'
