name: Rust Rewrite CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: SamChou19815/infra/actions/setup-node-project@main
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Format Check
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo lint
      - name: Test
        run: |
          cargo tc
          RUST=1 ./compile-repository.sh
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd crates/samlang-wasm && ./setup-generated-package.sh
