name: TSSA
on: pull_request

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: ".yarn/cache\n.pnp.js"
          key: "yarn-berry-${{ hashFiles('**/yarn.lock') }}"
          restore-keys: 'yarn-berry-'
      - name: Yarn Install
        run: yarn install --immutable
      - name: Analyze
        run: yarn tssa $(cat workspaces.json | jq '.information | .[] | .workspaceLocation' -r)
        env:
          USER_LOGIN: dev-sam-bot
          GITHUB_TOKEN: ${{ secrets.DEV_SAM_BOT_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
